# Generated by Django 2.1.5 on 2019-02-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processqueueaction',
            name='tracking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
