# Generated by Django 2.1.5 on 2019-02-05 17:04

from django.db import migrations, models
import napi.models


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0002_auto_20190205_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processqueueaction',
            name='tracking_id',
            field=models.AutoField(default=napi.models.sequence_id, primary_key=True, serialize=False),
        ),
    ]
