apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db-deployment
  labels:
    domain: {{ .Release.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      domain: {{ .Release.Name }}-db
  template:
    metadata:
      name: db-template
      labels:
        domain: {{ .Release.Name }}-db
    spec:
      containers:
        - name: {{ .Release.Name }}-db
          image: postgres:11
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-secret-config
          ports:
            - containerPort: 5432






