apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-deployment
  labels:
    domain: {{ .Release.Name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      domain: {{ .Release.Name }}-app
  template:
    metadata:
      name: app-template
      labels:
        domain: {{ .Release.Name }}-app
    spec:
      containers:
        - name: {{ .Release.Name }}-app
          image: {{.Values.local.image}}:{{ .Values.global.image.releaseTag}}
          imagePullPolicy: Always
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: appsecrets
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: name
                  name: appsecrets
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: appsecrets
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: appsecrets
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: appsecrets
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  key: broker_url
                  name: appsecrets
          ports:
            - containerPort: 8000
