apiVersion: v1
kind: Secret
metadata:
  name: appsecrets
data:
  user: {{.Values.global.db.user | b64enc}}
  name: {{.Values.global.db.name | b64enc}}
  password: {{.Values.global.db.password | b64enc}}
  host: {{.Values.global.db.host | b64enc }}
  port: {{.Values.global.db.port | toString | b64enc }}
